repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-added-large-files
    -   id: flake8
        language_version: python3.7
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: name-tests-test
    -   id: name-tests-test
        args: ['--django']
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: double-quote-string-fixer
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3.7
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3.7
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
-  repo: local
   hooks:
   -   id: pytest
       name: Check pytest unit tests pass
       stages: [push]
       entry: poetry run task test
       pass_filenames: false
       always_run: true
       language: system
       types: [python]
